// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadInfo } from "./DownloadInfo";
import type { MultiDownloadInfo } from "./MultiDownloadInfo";
import type { PackageInfo } from "./PackageInfo";

export type InstallationStatus = { "kind": "Initial" } | { "kind": "CheckingLatestReaperVersion" } | { "kind": "DownloadingReaper", download: DownloadInfo, } | { "kind": "InstalledReaper" } | { "kind": "CheckingLatestReaPackVersion" } | { "kind": "DownloadingReaPack", download: DownloadInfo, } | { "kind": "InstalledReaPack" } | { "kind": "DownloadingRepositoryIndexes", download: MultiDownloadInfo, } | { "kind": "ParsingRepositoryIndexes" } | { "kind": "PreparingPackageInstallation" } | { "kind": "DownloadingPackageFiles", download: MultiDownloadInfo, } | { "kind": "InstallingPackage", package: PackageInfo, } | { "kind": "Done" };