// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Package } from "./Package";
import type { RemoteFile } from "./RemoteFile";

export type InstallationStatusEvent = { "kind": "Idle" } | { "kind": "CheckingLatestReaperVersion" } | { "kind": "DownloadingReaper", file: RemoteFile, } | { "kind": "CheckingLatestReaPackVersion" } | { "kind": "DownloadingReaPack", file: RemoteFile, } | { "kind": "InitializingReaPack" } | { "kind": "DownloadingRepositoryIndex", file: RemoteFile, } | { "kind": "DownloadingPackageFile", file: RemoteFile, package: Package, } | { "kind": "InstallingPackage", package: Package, } | { "kind": "Done" };