// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationStatus } from "./InstallationStatus";
import type { ReabootError } from "./ReabootError";
import type { ResolvedReabootConfig } from "./ResolvedReabootConfig";

export type ReabootEvent = { "kind": "Error", error: ReabootError, } | { "kind": "ConfigResolved", state: ResolvedReabootConfig, } | { "kind": "InstallationStatusChanged", status: InstallationStatus, };