// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReabootConfig } from "./ReabootConfig";

export type ReabootCommand = { "kind": "Configure", config: ReabootConfig, } | { "kind": "StartInstallation" } | { "kind": "CancelInstallation" };