[workspace]
resolver = "2"
members = ["src-lib", "src-reapack", "src-tauri"]

[workspace.dependencies]
reaboot-lib = { path = "src-lib" }
tauri = "1"
serde = "1"
serde_json = "1"
tokio = "1"
ts-rs = "8.0.0"
reqwest = "0.11.26"
reqwest-middleware = "0.2.5"
reqwest-retry = "0.4.0"
anyhow = "1.0.81"
futures = "0.3.30"
tempdir = "0.3.7"
serde-xml-rs = "0.6.0"
time = "0.3.34"