// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for confirmation by the user.
 */
export type ConfirmationRequest = { message: string, yes_label: string, no_label: string | null, };