// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallerConfig } from "./InstallerConfig";

/**
 * A simple fire-and-forget command sent from the frontend to the backend.
 */
export type ReabootCommand = { "kind": "ConfigureInstallation", config: InstallerConfig, } | { "kind": "StartInstallation" } | { "kind": "StartReaper" } | { "kind": "StartReaperInstaller", path: string, } | { "kind": "Confirm", answer: boolean, };
