// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaperPlatform } from "./ReaperPlatform";

/**
 * Basic configuration-independent information gathered by the backend.
 */
export type ReabootBackendInfo = { 
/**
 * Resource directory of the main REAPER installation.
 *
 * If `None`, that means it couldn't be determined for some reason. Should be rare.
 */
main_reaper_resource_dir: string | null, 
/**
 * Whether this resource directory exists already.
 */
main_reaper_resource_dir_exists: boolean, 
/**
 * Targeted REAPER platform, derived from the OS and architecture for which ReaBoot itself
 * was compiled.
 *
 * If `None`, that means it couldn't be determined for some reason. Should be rare.
 */
inherent_reaper_platform: ReaperPlatform | null, };