// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReaperPlatform = "macos-arm64" | "macos-i386" | "macos-x86_64" | "windows-x86" | "windows-x64" | "linux-aarch64" | "linux-armv7l" | "linux-i686" | "linux-x86_64";
