// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReaperPlatform = "MacOsAarch64" | "MacOsX86" | "MacOsX86_64" | "WindowsX86" | "WindowsX64" | "LinuxAarch64" | "LinuxArmv7l" | "LinuxI686" | "LinuxX86_64";