// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Recipe = { name: string, website?: string, manufacturer?: string, logo?: string, package_urls: Array<string>, };