// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaperPlatform } from "./ReaperPlatform";
import type { ReaperResourceDir } from "./ReaperResourceDir";
import type { VersionRef } from "./VersionRef";

/**
 * Resolved installer configuration (derived from the frontend installer config).
 */
export type ResolvedInstallerConfig = { 
/**
 * Resolved REAPER resource directory.
 */
reaper_resource_dir: ReaperResourceDir, 
/**
 * Whether the resolved REAPER resource directory exists.
 */
reaper_resource_dir_exists: boolean, 
/**
 * Whether the resolved REAPER resource directory belongs to the main REAPER installation
 * or to a portable REAPER installation.
 */
portable: boolean, 
/**
 * Resolved REAPER platform.
 */
platform: ReaperPlatform, 
/**
 * Resolved package URLs (includes URLs of packages that will be installed anyway).
 */
package_urls: Array<string>, num_download_retries: number, temp_parent_dir: string, keep_temp_dir: boolean, concurrent_downloads: number, dry_run: boolean, reaper_version: VersionRef, skip_failed_packages: boolean, };