name: ReaLearn
package_sets:
  - repository_url: https://github.com/helgoboss/reaper-packages/raw/master/index.xml
    packages:
      - category: Extensions
        name: ReaLearn-x64
        version: latest
  - repository_url: https://github.com/ReaTeam/ReaScripts/raw/master/index.xml
    packages:
      - category: Various
        name: rodilab_Color palette.lua
        version: latest-stable