// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A package path uniquely identifies a package within a repository index without referring to
 * a specific version of that package.
 *
 * # Examples
 *
 * # Structure
 *
 * A package path follows this schema:
 *
 * - **PACKAGE_PATH =** `{CATEGORY}/{PACKAGE_NAME}`
 * - **VERSION_REF =** `{VERSION_NAME}` or `latest` or `latest-pre`
 */
export type PackagePath = { 
/**
 * May contain `/` characters.
 */
category: string, 
/**
 * The package name is a file name, so it must not contain any `/` characters.
 */
package_name: string, };
