// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackagePath } from "./PackagePath";
import type { VersionRef } from "./VersionRef";

/**
 * A package version reference uniquely identifies a specific version of a package within
 * a repository index.
 *
 * # Examples
 *
 * - `p=Various/rodilab_Color%20palette.lua&v=1.2.3-pre`
 *
 * # Structure
 *
 * A version reference follows this schema:
 *
 * - **PACKAGE_VERSION_REF =** `p={PACKAGE_PATH}&v={VERSION_REF}`
 * - **PACKAGE_PATH =** `{CATEGORY}/{PACKAGE_NAME}`
 * - **VERSION_REF =** `{VERSION_NAME}` or `latest` or `latest-pre`
 *
 * - It's built like a typical URL query string, so it's made of `=`-delimited key-value pairs
 *   that are separated by `&` characters.
 * - Keys and values are encoded with the `application/x-www-form-urlencoded` encoding.
 * - The order of the key-value pairs is irrelevant.
 * - `p` is required.
 * - `v` is optional and defaults to `latest`.
 */
export type PackageVersionRef = { package_path: PackagePath, version_ref: VersionRef, };
