// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a specific package version.
 *
 * # Structure
 *
 * - **VERSION_REF =** `{VERSION_NAME}` or `latest` or `latest-pre`
 */
export type VersionRef = "latest" | "latest-pre" | string;
