// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an ongoing file download.
 */
export type DownloadInfo = { 
/**
 * A human-friendly label for the download.
 */
label: string, 
/**
 * Remote URL from which we are downloading.
 */
url: string, 
/**
 * Destination file on the local file system.
 */
file: string, };
