// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Feature = { name: string, default?: boolean | null, description?: string | null, packages?: Array<string> | null, };
