// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadInfo } from "./DownloadInfo";
import type { MultiDownloadInfo } from "./MultiDownloadInfo";
import type { PackageInfo } from "./PackageInfo";

export type InstallationStage = { "kind": "NothingInstalled" } | { "kind": "CheckingLatestReaperVersion" } | { "kind": "DownloadingReaper", download: DownloadInfo, } | { "kind": "ExtractingReaper" } | { "kind": "InstalledReaper" } | { "kind": "PreparingTempDirectory" } | { "kind": "DownloadingRepositoryIndexes", download: MultiDownloadInfo, } | { "kind": "ParsingRepositoryIndexes" } | { "kind": "PreparingPackageDownloading" } | { "kind": "DownloadingPackageFiles", download: MultiDownloadInfo, } | { "kind": "UpdatingReaPackState" } | { "kind": "ApplyingReaPackState" } | { "kind": "ApplyingPackage", package: PackageInfo, } | { "kind": "Failed", display_msg: string, } | { "kind": "Finished" };