// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an ongoing file download.
 */
export type MultiDownloadInfo = { in_progress_count: number, success_count: number, error_count: number, total_count: number, };
