// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Basic information about a package.
 */
export type PackageInfo = { name: string, desc: string, version: string, author: string, };