// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageDescriptor } from "./PackageDescriptor";

/**
 * A collection of packages within one repository.
 */
export type PackageSet = { 
/**
 * URL of the repository to which all packages in this set belong.
 */
repository_url: string, 
/**
 * Packages in this set.
 */
packages: Array<PackageDescriptor>, };