// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaperTarget } from "./ReaperTarget";

/**
 * Command for configuring the installation process.
 */
export type ReabootConfig = { 
/**
 * Custom REAPER resource directory, most likely the one of a portable REAPER installation.
 *
 * If `None`, we will use the resource directory of the main installation.
 */
custom_reaper_resource_dir?: string, 
/**
 * A list of package URLs pointing to packages to be installed.
 *
 * These recipes will be installed *in addition* to those that are going to be installed
 * anyway (if the installer is branded).
 */
package_urls: Array<string>, 
/**
 * Custom REAPER target.
 */
custom_reaper_target?: ReaperTarget, };