// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationStage } from "./InstallationStage";
import type { ReabootBackendInfo } from "./ReabootBackendInfo";
import type { ReabootError } from "./ReabootError";
import type { ResolvedInstallerConfig } from "./ResolvedInstallerConfig";

export type ReabootEvent = { "kind": "Error", error: ReabootError, } | { "kind": "BackendInfoChanged", info: ReabootBackendInfo, } | { "kind": "ConfigResolved", config: ResolvedInstallerConfig, } | { "kind": "InstallationStageChanged", stage: InstallationStage, };