// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallationStage } from "./InstallationStage";
import type { ReabootError } from "./ReabootError";
import type { ResolvedReabootConfig } from "./ResolvedReabootConfig";

export type ReabootEvent = { "kind": "Error", error: ReabootError, } | { "kind": "ConfigResolved", config: ResolvedReabootConfig, } | { "kind": "InstallationStageChanged", stage: InstallationStage, };