// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";

export type Recipe = { name: string, description?: string, author?: string, website?: string, skip_additional_packages?: boolean, required_packages?: Array<string>, features?: Record<string, Feature>, };