// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaperPlatform } from "./ReaperPlatform";
import type { ReaperResourceDir } from "./ReaperResourceDir";
import type { VersionRef } from "./VersionRef";

export type ResolvedInstallerConfig = { reaper_resource_dir: ReaperResourceDir, reaper_resource_dir_exists: boolean, reaper_resource_dir_is_portable: boolean, platform: ReaperPlatform, package_urls: Array<string>, num_download_retries: number, temp_parent_dir: string, keep_temp_dir: boolean, concurrent_downloads: number, dry_run: boolean, reaper_version: VersionRef, skip_failed_packages: boolean, };